# Generated by Django 5.0.6 on 2024-05-22 11:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client',
            old_name='full_name',
            new_name='first_name',
        ),
        migrations.RenameField(
            model_name='client',
            old_name='surname',
            new_name='last_name',
        ),
    ]
